<a href="https://colab.research.google.com/github/mr-alamdari/NLP-Word-Embeddings-Beginner/blob/main/NLP_Word_Embeddings_Beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
import collections

nltk.download('punkt')

In [4]:
!wget https://raw.githubusercontent.com/amanjeetsahu/Natural-Language-Processing-Specialization/master/Natural%20Language%20Processing%20with%20Probabilistic%20Models/Week%204/shakespeare.txt

--2022-04-17 07:49:37--  https://raw.githubusercontent.com/amanjeetsahu/Natural-Language-Processing-Specialization/master/Natural%20Language%20Processing%20with%20Probabilistic%20Models/Week%204/shakespeare.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 306996 (300K) [text/plain]
Saving to: ‘shakespeare.txt’

shakespeare.txt     100%[===================>] 299.80K  --.-KB/s    in 0.03s   

2022-04-17 07:49:37 (9.69 MB/s) - ‘shakespeare.txt’ saved [306996/306996]



In [5]:
with open('shakespeare.txt', 'r') as f:
  data = f.read()

In [15]:
data = re.sub(r'[,!?:-]', '.', data)
data = nltk.tokenize.word_tokenize(data)
data = [char.lower() for char in data if char.isalpha() or char=='.']

In [20]:
len(data)

60389

In [21]:
frquency_distribution = nltk.FreqDist(word for word in data)

In [23]:
len(frquency_distribution)

5772

In [26]:
frquency_distribution.most_common(30)

[('.', 9086),
 ('the', 1521),
 ('and', 1394),
 ('i', 1252),
 ('to', 1159),
 ('of', 1093),
 ('my', 857),
 ('that', 781),
 ('in', 770),
 ('you', 748),
 ('a', 742),
 ('is', 630),
 ('not', 559),
 ('for', 467),
 ('it', 460),
 ('with', 441),
 ('his', 434),
 ('but', 417),
 ('me', 417),
 ('your', 397),
 ('be', 395),
 ('thy', 359),
 ('this', 355),
 ('he', 353),
 ('so', 352),
 ('thou', 332),
 ('have', 327),
 ('as', 315),
 ('her', 281),
 ('him', 277)]

In [28]:
data_counter = collections.Counter(data)

In [31]:
data_counter

Counter({'o': 99,
         'for': 467,
         'a': 742,
         'muse': 18,
         'of': 1093,
         'fire': 22,
         '.': 9086,
         'that': 781,
         'would': 138,
         'ascend': 1,
         'the': 1521,
         'brightest': 2,
         'heaven': 48,
         'invention': 9,
         'kingdom': 6,
         'stage': 3,
         'princes': 4,
         'to': 1159,
         'act': 35,
         'and': 1394,
         'monarchs': 2,
         'behold': 13,
         'swelling': 1,
         'scene': 34,
         'then': 132,
         'should': 102,
         'warlike': 4,
         'harry': 1,
         'like': 95,
         'himself': 23,
         'assume': 1,
         'port': 3,
         'mars': 12,
         'at': 131,
         'his': 434,
         'heels': 3,
         'leash': 1,
         'in': 770,
         'hounds': 2,
         'famine': 3,
         'sword': 16,
         'crouch': 1,
         'employment': 2,
         'but': 417,
         'pardon': 20,
         'gentl

In [32]:
def word_index_spliter(data):

  word2Ind, Ind2word = {}, {}
  words = sorted(list(set(data)))    

  for index, k in enumerate(words):
    word2Ind[k]  = index
    Ind2word[index] = k
  
  return word2Ind, Ind2word

In [33]:
word2Ind, Ind2word = word_index_spliter(data)

In [39]:
rand_ind = np.random.randint(0, len(word2Ind))
rand_word = Ind2word[rand_ind]
print(word2Ind[rand_word], rand_word)

4934 sweetest


In [43]:
def weights_initialization(n, v, seed=1):
  
  np.random.seed(seed)
  w1 = np.random.random((n, v))
  w2 = np.random.random((v, n))
  b1 = np.random.random((n, 1))
  b2 = np.random.random((v, 1))

  return w1, w2, b1, b2

In [44]:
w1, w2, b1, b2 = weights_initialization(4, 8)

In [45]:
w1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01,
        2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01],
       [4.17304802e-01, 5.58689828e-01, 1.40386939e-01, 1.98101489e-01,
        8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01],
       [8.76389152e-01, 8.94606664e-01, 8.50442114e-02, 3.90547832e-02,
        1.69830420e-01, 8.78142503e-01, 9.83468338e-02, 4.21107625e-01]])

In [46]:
b1

array([[0.04995346],
       [0.53589641],
       [0.66379465],
       [0.51488911]])

In [47]:
print(w1.shape, b1.shape)

(4, 8) (4, 1)


In [48]:
print(w2.shape, b2.shape)

(8, 4) (8, 1)


In [97]:
softmax = lambda z: np.exp(z) / np.sum(np.exp(z), axis=0)

In [99]:
arr = np.array([[1, 2, 3], [1, 1, 1]])
softmax(arr)

array([[0.5       , 0.73105858, 0.88079708],
       [0.5       , 0.26894142, 0.11920292]])

In [100]:
def forward_prop(x, w1, w2, b1, b2):

  hidden_layer = w1.dot(x) + b1
  
  #1
  # hidden_layer[hidden_layer <= 0] = 0
  # activation_layer = hidden_layer
  
  #2
  activation_layer = np.maximum(0, hidden_layer)
  
  output_layer = w2.dot(activation_layer) + b2
  return output_layer, activation_layer

In [102]:
x = np.array([[0, 1, 0]]).T

w1, w2, b1, b2 = weights_initialization(2, 3)

out, hid = forward_prop(x, w1, w2, b1, b2)

In [103]:
print(out)

[[0.55379268]
 [1.58960774]
 [1.50722933]]


In [104]:
print(hid)

[[0.92477674]
 [1.02487333]]
